magic_numbers:

  # ====== For clarity =======

  # final_similarity_score = (sim_score_from_col_name*clarity_normalizing_factor_for_col_name) + (sim_score_from_col_val * clarity_normalizing_factor_for_col_value)
  clarity_normalizing_factor_for_col_name: 0.5
  clarity_normalizing_factor_for_col_value: 0.5

  carat_normalizing_factor_for_col_name: 0.65
  carat_normalizing_factor_for_col_value: 0.35

  color_normalizing_factor_for_col_name: 0.5
  color_normalizing_factor_for_col_value: 0.5

  # This is used during post-processing stage
  # where we transform non-standard value to standard value.
  # There while using the string_similarity function we need this threshold parameter
  shape_similarity_transform_df_threshold: 0.7
  
  fluor_normalizing_factor_for_col_name: 0.5
  fluor_normalizing_factor_for_col_value: 0.5
  fluor_similarity_transform_df_threshold: 0.3

  raprate_normalizing_factor_for_col_name: 0.5
  raprate_normalizing_factor_for_col_value: 0.5

  measurement_normalizing_factor_for_col_name: 0.4
  measurement_normalizing_factor_for_col_value: 0.6
  
  cut_normalizing_factor_for_col_name: 0.5
  cut_normalizing_factor_for_col_value: 0.5
  cut_similarity_transform_df_threshold: 0.7

  polish_normalizing_factor_for_col_name: 0.5
  polish_normalizing_factor_for_col_value: 0.5

  sym_normalizing_factor_for_col_name: 0.5
  sym_normalizing_factor_for_col_value: 0.5
  
  table_normalizing_factor_for_col_name: 0.5
  table_normalizing_factor_for_col_value: 0.5

  comments_normalizing_factor_for_col_name: 0.8
  comments_normalizing_factor_for_col_value: 0.2

  ppc_normalizing_factor_for_col_name: 0.5
  ppc_normalizing_factor_for_col_value: 0.5

  disc_normalizing_factor_for_col_name: 0.6
  disc_normalizing_factor_for_col_value: 0.4

  amt_normalizing_factor_for_col_name: 0.5
  amt_normalizing_factor_for_col_value: 0.5

  raptotal_normalizing_factor_for_col_name: 0.5
  raptotal_normalizing_factor_for_col_value: 0.5

  stockref_normalizing_factor_for_col_name: 0.5
  stockref_normalizing_factor_for_col_value: 0.5

  report_normalizing_factor_for_col_name: 0.5
  report_normalizing_factor_for_col_value: 0.5

  threshold_for_selection: 0.60